---
HOSTS:
  el10:
    platform: el-10-x86_64
    box: generic/rocky10
    hypervisor: "<%= ENV.fetch('BEAKER_HYPERVISOR', 'vagrant') %>"
    family: rocky-linux-cloud/rocky-linux-10
    gce_machine_type: n1-standard-2
CONFIG:
  log_level: verbose
  synced_folder: disabled
  type: aio
  vagrant_memsize: 256
  puppet_collection: "<%= ENV.fetch('BEAKER_PUPPET_COLLECTION', 'openvox8') %>"
